name = "blas_interface"
version = "0.1.0"
license = "MIT"
author = "0382"
maintainer = "18322825326@163.com"
copyright = "Copyright 2024, 0382"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

